=== Letsmoe/hydra/hydra.schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema",
	"$id": "https://continuum-ai.de/hydra/hydra.schema.json",
	"title": "Hydra",
	"description": "Hydra is a package for managing monorepos written in any language.",
	"type": "object",
	"required": ["dirs", "entry", "out"],
	"properties": {
		"dirs": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"match": {
						"type": "string",
						"description": "A RegExp string to match a potential folder candidate to - if it matches, the rule will be followed."
					},
					"outName": {
						"type": "string",
						"description": "The name of the folder to output to once a folder is moved."
					},
					"strategy": {
						"type": "string",
						"enum": ["default", "root"],
						"default": "default",
						"description": "The strategy to follow when moving, default will output the folder inside the package directory whilst root will revert the order of path parts."
					}
				},
				"required": ["match", "outName"]
			}
		},
		"entry": {
			"type": "string",
			"description": "The entry point of the project.",
			"default": "./"
		},
		"out": {
			"type": "string",
			"description": "The output directory of the project.",
			"default": "../out/"
		},
		"options": {
			"type": "object",
			"properties": {
				"moveTopLevelFiles": {
					"type": "boolean",
					"description": "If true, the top level files will be moved to the build directory.",
					"default": false
				},
				"clear": {
					"type": "boolean",
					"description": "If true, the build directory will be cleared before the build process starts.",
					"default": false
				}
			}
		},
		"watch": {
			"type": "string",
			"description": "The folder to watch, can be left blank if not path shall be watched.",
			"default": ""
		},
		"ignore": {
			"type": "array",
			"description": "An array containing regular expressions to match against files that shall be ignored.",
			"default": [".*node_modules.*", "\\.gitignore"]
		}
	}
}

=== Letsmoe/hydra/test/hydra.test.config.json
{
	"entry": "./folders/",
	"out": "./out/",
	"dirs": [
		{
			"match": ".*docs.*",
			"outName": "docs",
			"strategy": "root"
		},
		{
			"match": ".*dist.*",
			"outName": "",
			"strategy": "default"
		}
	],
	"options": {
		"clear": false,
		"moveTopLevelFiles": true
	},
	"watch": "./folders/",
	"ignore": [".*node_modules.*", "\\.gitignore"]
}
